spring:
  application:
    name: identity-service
server:
  port: 8080
  servlet:
    context-path: /identity-service
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

