spring:
  application:
    name: identity-service
  devtools:
    restart:
      enabled: false
    remote:
      enabled: false
server:
  port: 8080
  servlet:
    context-path: /identity-service
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
