server:
  port: 8888

app:
  api-prefix: /api
  strip-prefix: 1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Cho phép API Gateway phát hiện các dịch vụ từ Eureka
      routes:
        - id: identity-service
          uri: lb://identity-service  # Sử dụng Eureka để phát hiện dịch vụ identity-service
          predicates:
            - Path=${app.api-prefix}/identity-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: user-service
          uri: lb://user-service  # Sử dụng Eureka để phát hiện dịch vụ user-service
          predicates:
            - Path=${app.api-prefix}/user-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: notification-service
          uri: lb://notification-service  # Sử dụng Eureka để phát hiện dịch vụ notification-service
          predicates:
            - Path=${app.api-prefix}/notification-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: post-service
          uri: lb://post-service  # Sử dụng Eureka để phát hiện dịch vụ post-service
          predicates:
            - Path=${app.api-prefix}/post-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: file-service
          uri: lb://file-service  # Sử dụng Eureka để phát hiện dịch vụ file-service
          predicates:
            - Path=${app.api-prefix}/file-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: aggregation-service
          uri: lb://aggregation-service  # Sử dụng Eureka để phát hiện dịch vụ aggregation-service
          predicates:
            - Path=${app.api-prefix}/aggregation-service/**
          filters:
            - StripPrefix=${app.strip-prefix}
