server:
  port: 8888

app:
  api-prefix: /api
  strip-prefix: 1
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/user-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: post-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/post-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: file-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/file-service/**
          filters:
            - StripPrefix=${app.strip-prefix}

        - id: aggregation-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/aggregation-service/**
          filters:
            - StripPrefix=${app.strip-prefix}
