server:
  servlet:
    context-path: /dw-demo
  port: 8888

spring:
  application:
    name: data-warehouse
  datasource:
    url: "jdbc:mysql://localhost:3306/data-ware-house"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
