server:
  port: 8084
  servlet:
    context-path: /file-service

spring:
  application:
    name: file-service
  datasource:
    url: "jdbc:mysql://localhost:3306/job-csm-file-service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: false
    remote:
      enabled: false
cloudinary:
  cloud_name: dter3mlpl
  api_key: 899244476586798
  api_secret: 3uCxvocAtzZCFX0BqvXPhYcGMXg

eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
