server:
  port: 8081
  servlet:
    context-path:/user-service

spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/job-social-media_user-service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"


